"""Graduate and trainee accounting roles in the UK: audit, tax, and finance
trainee schemes, typically with study support towards ACA, ACCA, or CIMA."""

from ..profile import Profile

LABEL = "Accounting & finance (graduate, UK)"
DESCRIPTION = ("Graduate schemes and trainee roles in audit, tax and finance, "
               "ideally with ACA/ACCA/CIMA study support. Blocks qualified "
               "and senior roles.")

PROFILE = Profile(
    name="",
    preset="accounting_graduate",
    locations=["London"],
    radius_miles=15,
    job_category="accounting",
    target_titles={
        # Graduate schemes and trainee contracts — the strongest fit
        "graduate accountant": 30,
        "trainee accountant": 30,
        "trainee chartered accountant": 30,
        "aca trainee": 30,
        "acca trainee": 30,
        "cima trainee": 28,
        "graduate audit": 30,
        "audit graduate": 30,
        "audit associate": 28,
        "audit trainee": 28,
        "trainee auditor": 28,
        "assurance associate": 28,
        "graduate tax": 28,
        "tax graduate": 28,
        "tax associate": 26,
        "tax trainee": 26,
        "graduate finance": 26,
        "finance graduate": 26,
        # Entry-level finance roles that often fund a qualification
        "junior accountant": 26,
        "assistant accountant": 24,
        "accounts assistant": 22,
        "finance assistant": 20,
        "accounts payable": 16,
        "accounts receivable": 16,
    },
    domain_terms={
        "study support": 10,
        "aca qualification": 10,
        "aca training": 10,
        "acca": 10,
        "icaew": 8,
        "cima": 8,
        "aat": 6,
        "chartered accountant": 6,
        "professional qualification": 8,
        "fully funded": 6,
        "graduate scheme": 8,
        "graduate programme": 8,
        "graduate": 6,
        "entry level": 8,
        "no experience": 8,
        "2:1": 4,
        "external audit": 8,
        "audit": 6,
        "assurance": 4,
        "tax": 4,
        "financial reporting": 6,
        "ifrs": 6,
        "uk gaap": 6,
        "reconciliation": 5,
        "month end": 5,
        "month-end": 5,
        "xero": 4,
        "sage": 4,
        "excel": 3,
    },
    title_blockers=[
        "head of",
        "director",
        "vp ",
        "vice president",
        "senior",
        "lead ",
        "principal",
        "manager",
        "partner",
        "chief",
        "controller",
        "supervisor",
        "experienced",
        "newly qualified",
        "nq ",
        "fully qualified",
        "qualified accountant",
    ],
    experience_blockers=[
        "3+ years",
        "4+ years",
        "5+ years",
        "6+ years",
        "7+ years",
        "10+ years",
        "three years",
        "four years",
        "five years",
        "minimum of 3 years",
        "minimum of 5 years",
        "fully qualified",
        "newly qualified",
        "must be qualified",
        "aca qualified",
        "acca qualified",
        "cima qualified",
        "aca/acca qualified",
    ],
    # Graduate pay: roughly £28-35k in London, £22-28k elsewhere.
    salary_bands=[[30_000, 10], [25_000, 5], [20_000, 0], [0, -8]],
    contract_bonus=0,
    # Graduate schemes are titled every which way ("Assurance Graduate
    # Programme 2027"), so strong domain vocabulary can stand in for a title.
    domain_only_threshold=15,
)
